# Generated by Django 2.0.5 on 2020-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['my_order'], 'verbose_name': 'Voter', 'verbose_name_plural': 'Voters'},
        ),
        migrations.AddField(
            model_name='voter',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
