# Generated by Django 2.0.5 on 2020-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200814_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
