# Generated by Django 2.0.5 on 2020-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20200814_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='position',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
