# Generated by Django 2.2 on 2020-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20200815_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCodeEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('pass_code', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
