# Generated by Django 2.2 on 2020-08-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_passcodeemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassCodeEmails',
            new_name='PassCodeEmail',
        ),
        migrations.AlterField(
            model_name='voter',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='full name'),
        ),
    ]
